patch pom.xml files and build files to align with Altiscales hadoop lib and classpath location, and Hadoop2 version label, added kmean dataset for testcase

diff --git a/bin/run-example2 b/bin/run-example2
--- a/bin/run-example2
+++ b/bin/run-example2
@@ -44,15 +44,17 @@ fi
 # to avoid the -sources and -doc packages that are built by publish-local.
 EXAMPLES_DIR="$FWDIR"/examples
 SPARK_EXAMPLES_JAR=""
-if [ -e "$EXAMPLES_DIR"/target/scala-$SCALA_VERSION/*assembly*[0-9Tg].jar ]; then
-  export SPARK_EXAMPLES_JAR=`ls "$EXAMPLES_DIR"/target/scala-$SCALA_VERSION/*assembly*[0-9Tg].jar`
+if [ -e "$EXAMPLES_DIR"/target/*examples*[0-9Tg].jar ]; then
+  export SPARK_EXAMPLES_JAR=`ls "$EXAMPLES_DIR"/target/*examples*[0-9Tg].jar`
 fi
 if [[ -z $SPARK_EXAMPLES_JAR ]]; then
-  echo "Failed to find Spark examples assembly in $FWDIR/examples/target" >&2
-  echo "You need to build Spark with sbt/sbt assembly before running this program" >&2
+  echo "Failed to find Spark examples JARs in $FWDIR/examples/target" >&2
   exit 1
 fi
 
+SPARK_JAR=""
+export SPARK_JAR=`ls "$FWDIR"/assembly/target/scala-$SCALA_VERSION/spark-assembly*hadoop*.jar`
+export SPARK_YARN_APP_JAR=$SPARK_EXAMPLES_JAR
 
 # Since the examples JAR ideally shouldn't include spark-core (that dependency should be
 # "provided"), also add our standard Spark classpath, built using compute-classpath.sh.
